@echo off

echo // Autogenerated via compileShaders.bat > shaders.h

:: VSPos
fxc /T vs_4_0 /E VSPos /Vn Shader_VSPos /Fh shader_vspos.h /Ges shaders.fx
echo #include "shader_vspos.h" >> shaders.h

:: PSColor
fxc /T ps_4_0 /E PSColor /Vn Shader_PSColor /Fh shader_pscolor.h /Ges shaders.fx
echo #include "shader_pscolor.h" >> shaders.h

:: PSTextureColor
fxc /T ps_4_0 /E PSTextureColor /Vn Shader_PSTextureColor /Fh shader_pstexturecolor.h /Ges shaders.fx
echo #include "shader_pstexturecolor.h" >> shaders.h
