@echo off

echo // Autogenerated via compileShaders.bat > shaders.h

:: VSPos
fxc /T vs_4_0 /E VSPos /Vn Shader_VSPos /Fh shader_vspos.h /Ges shaders.fx
echo #include "shader_vspos.h" >> shaders.h

:: PSYellow
fxc /T ps_4_0 /E PSYellow /Vn Shader_PSYellow /Fh shader_psyellow.h /Ges shaders.fx
echo #include "shader_psyellow.h" >> shaders.h
